services:
  db:
    image: postgres:latest
    container_name: car_service_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main_db
    ports:
      - "5313:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    
