version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: car_service_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main_db
    ports:
      - "5313:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: car_service_minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"  
      - "9001:9001" 
    volumes:
      - miniodata:/data
    command: server /data --console-address ":9001"
    
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: car_service_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmindata:/var/lib/pgadmin

volumes:
  pgdata:
  miniodata:
  pgadmindata:

    
