// <auto-generated />
using Car.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Car.Dal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250428114228_MakePhotoIdNullableForCar")]
    partial class MakePhotoIdNullableForCar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Car.Dal.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Primary key");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<string>("CarCondition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("car_condition")
                        .HasComment("Car condition");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("car_details");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("integer")
                        .HasColumnName("photo_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("PrioritySale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority_sale")
                        .HasComment("Car priority sale");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.ToTable("cars", (string)null);
                });

            modelBuilder.Entity("Car.Dal.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Extension")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("extension");

                    b.Property<byte[]>("PhotoBytes")
                        .HasColumnType("bytea")
                        .HasColumnName("photo_bytes");

                    b.HasKey("Id");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("Car.Dal.Models.Car", b =>
                {
                    b.HasOne("Car.Dal.Models.Photo", "Photo")
                        .WithOne("Car")
                        .HasForeignKey("Car.Dal.Models.Car", "PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_car_photo");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Car.Dal.Models.Photo", b =>
                {
                    b.Navigation("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
